[package]
name = "l0chlainn/signal"
description = "Yet another Signal"
version = "1.0.1"
license = "MIT"
authors = ["l0chlainn"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
